# Generated by Django 5.2 on 2025-06-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonprogress',
            name='completed',
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='status',
            field=models.CharField(choices=[('In Progress', 'IN_PRPOGRESS'), ('Completed', 'COMPLETED')], default='In Progress', max_length=20),
        ),
    ]
