# Generated by Django 5.2 on 2025-06-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_remove_lessonprogress_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonprogress',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='status',
            field=models.CharField(choices=[('In Progress', 'IN_PROGRESS'), ('Completed', 'COMPLETED')], default='In Progress', max_length=20),
        ),
    ]
